services:
  patient-service:
    container_name: patient-service
    image: patient-service:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    #    ports:
    #      - "4000:4000"
    depends_on:
      patient-service-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://patient-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - BILLING_SERVICE_ADDRESS=billing-service
      - BILLING_SERVICE_GRPC_PORT=9001
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    restart: always

  patient-service-db:
    container_name: patient-service-db
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5000:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/patient-service/data
    networks:
      - internal
    restart: always

  billing-service:
    container_name: billing-service
    image: billing-service:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4001/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      patient-service:
        condition: service_healthy
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    restart: always

  analytics-service:
    container_name: analytics-service
    image: analytics-service:latest
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4002/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      patient-service:
        condition: service_healthy
    ports:
      - "4002:4002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    restart: always

  auth-service:
    container_name: auth-service
    image: auth-service:latest
    ports:
      - "4005:4005"
    depends_on:
      auth-service-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-service-db:5432/db
      - SPRING_DATASOURCE_USERNAME=admin_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SQL_INIT_MODE=always
      - JWT_SECRET=S33ZQxAxGfD69XVB3q0v4Zl9uHD7hVsjkDPXMYe4GZw=
    #      - BILLING_SERVICE_ADDRESS=billing-service
    #      - BILLING_SERVICE_GRPC_PORT=9001
    #      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - internal
    restart: always

  auth-service-db:
    container_name: auth-service-db
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/auth-service/data
    networks:
      - internal
    restart: always

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    ports:
      - "4004:4004"
    networks:
      - internal
    restart: always

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 180s
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
      - KAFKA_KRAFT_CLUSTER_ID=yourBase64ClusterIDHere
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - internal
    restart: always

volumes:
  postgres-data:

networks:
  internal:
    driver: bridge
