### POST request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Doe with billing account",
  "address": "Test Address",
  "email": "john.doee2@xample.com",
  "dateOfBirth": "1993-05-05",
  "registeredDate": "2025-05-05"
}

###